version: '3.8'
services:
  app:
    build: .
    depends_on: [mysql]
    volumes:
      - ./src/main/resources/application-docker.properties:/app/application.properties
    ports:
      - "8081:8080"

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: fgsfds12
      MYSQL_DATABASE: banking_app
      MYSQL_USER: user
      MYSQL_PASSWORD: fgsfds12
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
