name: Java CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: fgsfds12
          MYSQL_DATABASE: banking_app
          MYSQL_USER: user
          MYSQL_PASSWORD: fgsfds12
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        run: ./mvnw package

      - name: Build and run with Docker Compose
        run: |
          docker-compose up --build -d
          docker-compose ps

      - name: Shutdown Docker Compose
        run: docker-compose down